### ISSUE TITLE
virtualbox-guest-modules-arch is no longer available

### ISSUE THREAD

**Issue by utuhiro78** [arcolinuxb/arco-xfce#2]
```
sh 30-build-the-iso-the-first-time.sh
error: target not found: virtualbox-guest-modules-arch
==> ERROR: Failed to install packages to new root
```

virtualbox-guest-modules-arch is no longer available, so we can't build arco-xfce.
https://www.archlinux.org/packages/community/x86_64/virtualbox-guest-modules-arch/

**Comment by arcolinuxz** [comment]
I just saw it 30 minutes ago - put a # in front of the line
