### ISSUE TITLE
arcolinux-variety-git-20.11-1 is an invalid or corrupted package

### ISSUE THREAD

**Issue by utuhiro78** [arcolinuxb/arco-xfce#3]
I couldn't build arco-xfce.
./30-build-the-iso-the-first-time.sh
```
error: arcolinux-variety-git: signature from "John Blevins <mail>" is unknown trust
:: File /var/cache/pacman/pkg/arcolinux-variety-git-20.11-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

Arcolinux is easy to use. Thanks for developing it.

**Comment by arcolinuxz** [comment]
delete your old and corrupt cache

`sudo pacman -Scc `

or

run nr 30

**Comment by arcolinuxz** [comment]
Just build ArcoLinuxD and installling it now

**Comment by arcolinuxz** [comment]
We have https://arcolinuxforum.com and discord for reporting issues.

**Comment by arcolinuxz** [comment]
Oh sorry I see now
Your are rolling and did not install ArcoLinux 20.11.9
Get the keys in.

https://arcolinuxforum.com/viewtopic.php?f=79&t=2214

**Comment by utuhiro78** [comment]
I added the keys. arcolinux-variety-git was installed successfully, but 
arcolinuxb-xfce-v21.01.3-x86_64.iso is not created.
Please check the log: [arco-xfce-git-20201211-log.txt](https://github.com/arcolinuxb/arco-xfce/files/5678797/arco-xfce-git-20201211-log.txt)

> Get the keys in.
> https://arcolinuxforum.com/viewtopic.php?f=79&t=2214

Is it possible to add the commands to "30-build-the-iso-the-first-time.sh" ? 

```
#Erik key
sudo pacman-key --recv-keys 74F5DE85A506BF64
...
sudo pacman-key --lsign-key 7EC1A5550718AB89
```

**Comment by arcolinuxz** [comment]
see you on https://arcolinuxforum.com
That is where we answer such questions.
