### ISSUE TITLE
please fix the isue so i can build the iso thanks for your awesome job

### ISSUE THREAD

**Issue by bojanstrkovski-21** [arcolinuxb/arco-xfce#4]
error: Can't load **_uri_** https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name

**Comment by bojanstrkovski-21** [comment]
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name

**Comment by arcolinuxz** [comment]
there is nothing to fix

it is on your end

my internet is working great

so url was found

**Comment by arcolinuxz** [comment]
`[mkarchiso] INFO: Done! GRUB set up for UEFI booting successfully.
[mkarchiso] INFO: Done! GRUB set up for UEFI booting successfully.
[mkarchiso] INFO: Preparing an /EFI directory for the ISO 9660 file system...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: Preparing an /EFI directory for the ISO 9660 file system...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: Cleaning up in pacstrap location...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: Creating SquashFS image, this may take some time...
Parallel mksquashfs: Using 16 processors
Creating 4.0 filesystem on /home/erik/arcolinuxb-build/iso/arch/x86_64/airootfs.sfs, block size 1048576.
[==========================\                                                       ]  70174/217442  32%`
